name: Hello workflow
on: push

jobs:
  backend:
    run-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        uses: echo "Testing backend"
  
  frontend:
    run-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: echo "Testing frontend"