name: Hello workflow
on: push

jobs:
  run-on: ubuntu-latest
  steps:
  
    - name: Checkout
      uses: actions/checkout@v4

  
    - run: | 
        echo "Repository: ${{ github.repository }}"  
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit SHA: ${{ github.sha }}"